
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'abstract address article author cierreAbstract cierreAddress cierreArticle cierreAuthor cierreCity cierreComment cierreCopyright cierreDate cierreEmail cierreEmphasis cierreEntry cierreEntrytbl cierreFirstname cierreHolder cierreImageObject cierreImportant cierreInfo cierreInformalTable cierreItemizedlist cierreLink cierreListItem cierreMediaObject cierrePara cierrePhone cierreRow cierreSection cierreSimpara cierreSimpleSection cierreState cierreStreet cierreSurname cierreTbody cierreTfoot cierreTgroup cierreThead cierreTitle cierreVideoObject cierreYear city comment contenido_texto copyright date doctype email emphasis entry entrytbl firstname holder imageData imageObject important info informalTable itemizedlist link listItem mediaObject para phone row section simpara simpleSection state street surname tbody tfoot tgroup thead title videoData videoObject year SIGMA : doctype ARTICLEARTICLE : article contenido_texto cierreArticle'
    
_lr_action_items = {'doctype':([0,],[2,]),'$end':([1,3,6,],[0,-1,-2,]),'article':([2,],[4,]),'contenido_texto':([4,],[5,]),'cierreArticle':([5,],[6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'SIGMA':([0,],[1,]),'ARTICLE':([2,],[3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> SIGMA","S'",1,None,None,None),
  ('SIGMA -> doctype ARTICLE','SIGMA',2,'p_SIGMA','parser_1.py',18),
  ('ARTICLE -> article contenido_texto cierreArticle','ARTICLE',3,'p_ARTICLE','parser_1.py',24),
]
